bash: new gpg_clean
bonus: new yesno

diff --git a/bash/functions b/bash/functions
--- a/bash/functions
+++ b/bash/functions
@@ -210,3 +210,54 @@ function osxdocker() {
   eval $(docker-machine env default)
   eval "\\docker $@"
 }
+
+function yesno() {
+    echo -n "$@ [y/N]"
+    old_stty_cfg=$(stty -g)
+    stty raw -echo ; answer=$(head -c 1) ; stty $old_stty_cfg # Care playing with stty
+    if echo "$answer" | grep -iq "^y" ;then
+        return 0
+    fi
+    return 1
+}
+
+function gpg_clean() {
+    # Clean up the GPG Keyring.  Keep it tidy.
+    # blog.lavall.ee
+    echo "Cleaning up the GPG keyring..."
+
+    for expiredKey in $(gpg2 --list-keys | awk '/^pub.* \[expired\: / {id=$2; sub(/^.*\//, "", id); print id}' | fmt -w 999 ); do
+        echo
+        echo "Found an expired key:"
+        echo
+        gpg2 --list-key "$expiredKey"
+        yesno "Delete it?"
+        if [ $? -eq 1 ]; then
+            echo " won't delete"
+            continue
+        fi
+        gpg2 --delete-keys "$expiredKey" #batch quiet bitbucket
+        if [ $? -eq 0 ]; then
+            echo " deleted"
+        else
+            echo " failed to delete"
+            exit 1
+        fi
+    done
+
+    echo
+    echo Verifying key integrity:
+    for keyid in $(gpg -k | grep ^pub | grep -v expired: | grep -v revoked: | cut -d/ -f2 | cut -d' ' -f1); do
+        echo -n "  $keyid"
+        gpg2 --batch --quiet --edit-key $keyid check clean cross-certify save quit > /dev/null 2>&1
+        if [ $? -eq 0 ]; then
+            echo " OK"
+        else
+            echo " FAIL"
+        fi
+    done
+
+    echo
+    echo Updating keys...
+    gpg2 --refresh-keys
+}
